### PR TITLE
process: Fix the way output is handled after process termination

### LINKED ISSUE #207: process: Make sure we don't miss any output
The way the agent code was written, it was forcing the end of the output (stdout/stderr) right after the process was returning. Instead, by properly closing all the remaining pipes, we should be able to wait for the proper end of stdout/stderr. This way, we won't miss any output before to return the exit code to the shim.

Refers to https://github.com/clearcontainers/runtime/issues/997

### PR DESCRIPTION
**Pull request by sboeuf**
This PR does a bit of cleanup, but it mainly fixes the way the agent should properly wait for the end of any process output, instead of forcing the closure of its output.

Fixes #207

### CODE REVIEW

**Comment by sboeuf** [comment]
Fixes https://github.com/clearcontainers/runtime/issues/997

**Comment by grahamwhaley** [comment]
@sboeuf do you think this is also related to https://github.com/kata-containers/agent/issues/125 ?

File: agent.go [hunk 1]
```diff
@@ -952,6 +952,35 @@ func (c *container) closeProcessPipes(pid string) {
...
+
+	errMsg := "Could not close process socket pair"
+
+	if proc == nil {
+		return fmt.Errorf("Container %s process %s no longer exists", cid, pid)
+	}
+
+	if proc.consoleSock != nil {
+		if err := proc.consoleSock.Close(); err != nil {
+			return fmt.Errorf(errMsg)
```
Comment (jodh-intel) [inline agent.go]: You don't need `Errorf()` as written. But how about making it as follows (here and below)?

```
return fmt.Errorf("%s: %s", errMsg, err)
```

Comment (jodh-intel) [reply agent.go]: (By that I mean you could just use `errors.New(errMsg)`).

Comment (sboeuf) [reply agent.go]: Yes let me change that ;)

**Comment by sboeuf** [comment]
@grahamwhaley no I don't think this is related. The whole logic behind getting stdout/stderr is handled differently with kata agent.

**Comment by sboeuf** [comment]
@jodh-intel PR updated.

**Review by jodh-intel — APPROVED** [review]
lgtm

**Review by grahamwhaley — APPROVED** [review]
Nicely broken out and written patches btw.
lgtm

**Comment by sboeuf** [comment]
@grahamwhaley thx ;)

**Comment by jcvenegas** [comment]
lgtm
agree with @grahamwhaley, makes easy to get the root cause. 


[Approved with PullApprove](https://pullapprove.com/clearcontainers/agent/pull-request/208/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/agent)
