### PR TITLE
mount: Use 9p2000.L version when mounting 9p filesystem

### LINKED ISSUE #214: mounts: add `version=9p2000.L` to agent mounts
Over on #211 we showed that moving to using `9p2000.L` as the mount type fixes a couple of symlink test fails, and has no particularly visible change in performance. Make the change at https://github.com/clearcontainers/agent/blob/master/syscall.go#L110

### PR DESCRIPTION
**Pull request by sboeuf**
Using 9p2000.L version helps passing more tests compared to the
standard version. The symlinks are handled in a better way.

Fixes #214

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Review by grahamwhaley — APPROVED** [review]
lgtm
nice pull out to the const.
Be interesting to see what the CIs think.

File: syscall.go [hunk 1]
```diff
@@ -32,6 +32,7 @@ import (
 
 const mountPerm = os.FileMode(0755)
 const devPath = "/dev"
+const 9pMntOptions = "trans=virtio,version=9p2000.L"
```
Comment (jodh-intel) [inline syscall.go]: This isn't valid as it starts with a numeric.

**Comment by sboeuf** [comment]
@devimc @amshinde @jcvenegas PTAL

**Review by amshinde — APPROVED** [review]
lgtm
